language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
solution: Portal2Boards.Net.sln
script:
  - dotnet restore
  - dotnet build src/Portal2Boards.Net/ -c Release
  - dotnet build src/Portal2Boards.Net.Test/ -c Release /p:DefineConstants="DON"
  - dotnet run -p src/Portal2Boards.Net.Test/ -c Release
